### ISSUE TITLE
Visual Studio 2013 にインストールできない

### ISSUE THREAD

**Issue by cRe-Mate** [codic-project/codic-vs-extension#1]
Visual Studio 2013 Professionalにおいて，インストーラーでインストール完了のメッセージが出たあと，Visual Studioを起動すると，

> 'CodicExtentsion.CodicExtensionPackage, CodicExtension, Version=1.0.0.0, Culture=Neutral, PublicKeyToken=null' パッケージは正しく読み込まれませんでした。
> 構成の変更または別の拡張機能のインストールが原因で問題が発生している可能性があります。
> ファイル 'C:\Users\UserName\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml' を調べると，より詳細な情報を取得することができます。

というエラーメッセージが出ます。
ツール>オプション>Codic Extensionの欄を開いたときも同様のエラーメッセージが出，
また「このプロパティページの読み込み中にエラーが発生しました」とでます。

ちなみに先のエラーメッセージ中のログファイルの中では，

> 419 ERROR 要求された型のうち 1 つまたは複数を読み込めませんでした。詳細については、LoaderExceptions プロパティを取得してください。 
> C:\USERS\USERNAME\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\UKF3YFRY.GHZ\CodicExtension.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/02/06 15:36:53.640 
> 420 ERROR ファイルまたはアセンブリ 'Microsoft.VisualStudio.Shell.10.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=xxxxx'、またはその依存関係の 1 つが読み込めませんでした。指定されたファイルが見つかりません。
> C:\USERS\USERNAME\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\UKF3YFRY.GHZ\CodicExtension.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/02/06 15:36:53.640 
> 421 ERROR ファイルまたはアセンブリ 'Microsoft.VisualStudio.Shell.10.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=xxxxx'、またはその依存関係の 1 つが読み込めませんでした。指定されたファイルが見つかりません。
> C:\USERS\USERNAME\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\UKF3YFRY.GHZ\CodicExtension.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2016/02/06 15:36:53.640 
> 
> 484 ERROR CreateInstance failed for package [CodicExtension.CodicExtensionPackage, CodicExtension, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] {GUID} 80070002 VisualStudio 2016/02/06 15:36:56.077 
> 485 ERROR End package load [CodicExtension.CodicExtensionPackage, CodicExtension, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] {GUID} 80004005 - E_FAIL VisualStudio 2016/02/06 15:36:56.077 

のようなエラーが見られます。

また，自分で追加した拡張機能はありません。
報告させていただきますが，初心者なので至らないところがあったら申し訳ありません。

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。
PCに2013をインストールしてみて調査してみます m(_ _)m

**Comment by kenji-namba** [comment]
v 1.0.3 で2013に対応しています。2012はもうちょっと待ってください m(_ _)m

**Comment by cRe-Mate** [comment]
ありがとうございます。
無事アクセストークンの設定までできました。
