### ISSUE TITLE
Visual Studio 2017で、ショートカットが利かない

### ISSUE THREAD

**Issue by taokato** [codic-project/codic-vs-extension#10]
Ver1.0.6 を利用しています。

"Ghost Doc"　と併用している所為か
「エディタ上で、Ctrl+Shift+D でネーミング生成するためのポップアップを開きます。」
の動作が無効となっています。

"Ghost Doc"側のショートカットを、「Ctrl+Shift+D 」から「Ctrl+Shift+K 」に変更しても同じでした。

**Comment by kenji-namba** [comment]
ご報告ありがとうございました。
挙動を確認してみます。

**Comment by kenji-namba** [comment]
ちなみにですが、TranslationSelection（codicのコマンド）には何のキーが割り当てられていますでしょうか？（環境→キーボード→「以下の文字列を含むコマンドを表示」から「TranslationSelection」で検索してみてください）

**Comment by taokato** [comment]
こんにちは

> TranslationSelection（codicのコマンド）には何のキーが割り当てられていますでしょうか？

Ctrl + Shift + d

**Comment by kenji-namba** [comment]
度々すいません。
おそらく、Ctrl+Shift+Dに割り当てられているコマンドがたくさんいるんだと思います。
お手数ですが、以下の2つを試していただけないでしょうか？
1) TranslationSelectionを割り当てる際に「使用する場所：テキストエディター」で限定してもだめでしょうか？
2) コマンドをCtrl+Shift+D以外（Ctrl+Shift+Alt+Dなど）で割り当ててもだめでしょうか？

**Comment by taokato** [comment]
こんにちは


   1. TranslationSelectionを割り当てる際に「使用する場所：テキストエディター」で限定してもだめでしょうか？
   2. コマンドをCtrl+Shift+D以外（Ctrl+Shift+Alt+Dなど）で割り当ててもだめでしょうか？

１．の質問が読めません。
vs2017 community を使っているので、
「使用する場所：テキストエディター」で限定 ???
意味が分かりません。

２．コマンドをCtrl+Shift+D以外 について
D --->  K
これに変えましたが、反応無し。


それ以外に見つかったバグ

英文の候補が出るボックスには、原文と英文が出ています。
この原文は、編集できるので文字操作を行ったところ
vs2017 が固まって落ちました。
つまり、vs2017 が再起動になりました。

重度のバグに相当と思われますので、早急な対処をお願いします。






2017年11月15日 16:46 kenji namba <notifications@github.com>:

**Comment by kenji-namba** [comment]
返事がおそくりました。

「使用する場所：テキストエディター」というのは、
すべてのテキストエディターを拡張したエディターという意味です。
VSのUIでそのように書かれています。

ポップアップ上で、文字操作（文字変換）を行った際に、
VSが落ちる問題については、以下と同様のケースだと思われます。
https://github.com/codic-project/codic-vs-extension/issues/9
（こちらの問題については、上記スレで対応します）
