### ISSUE TITLE
VSIXインストーラーで前提条件を解決できない旨のメッセージが表示される

### ISSUE THREAD

**Issue by MasterMiyanishi** [codic-project/codic-vs-extension#13]
VSIXインストーラーで以下のメッセージが表示され
VisualStudioProfessional2017のチェックボックスが押せません
以下のようなメッセージが表zいされています
『前提条件を解決できないため、この拡張機能は本製品にインストールできません。』

使用しているのはVisualStudioProfessional2017で最新バージョンまでアップデートしています

![image](https://user-images.githubusercontent.com/1345388/61284017-11de7e00-a7f9-11e9-8d81-7adf38ea090c.png)

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。
なんとなく原因がわかりましたので、近々対応します。

**Comment by kenji-namba** [comment]
おまたせしました。
最新バージョン 1.0.8 で対応していますので、ご確認ください。
問題ないようでしたら、ご報告頂けますと助かります。

**Comment by MasterMiyanishi** [comment]
ご対応ありがとうございます
遅くなりましたが確認ができました
問題なく動作します！使わせていただきます！
ありがとうございました！！！

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。
解決したという事ですので、このissueはクローズさせていただきます。
