### ISSUE TITLE
ショートカットキーを押すとエラーになる

### ISSUE THREAD

**Issue by inchos0928** [codic-project/codic-vs-extension#14]
Visual Studio2015でショートカットキーを押すと、下記の画像のようなエラーメッセージが表示されます。
また、[ツール]→[オプション]→[Codic Extension]を選択すると強制終了されてしまいます。
どのように対応すればよろしいでしょうか。
宜しくお願い致します。
![image](https://user-images.githubusercontent.com/52982301/61337863-04190f00-a872-11e9-90de-7a68ef1ed84a.png)

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。
言及しているサイトがありましたので、こちらを参考に近々対応します。
https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/

**Comment by kenji-namba** [comment]
おまたせしました。
最新バージョン 1.0.8 で対応していますので、ご確認ください。
問題ないようでしたら、ご報告頂けますと助かります。

**Comment by inchos0928** [comment]
ご対応ありがとうございます。
無事機能いたしました。
今後ともよろしくお願いいたします。
