### ISSUE TITLE
入力カーソルが、背景色と同化して見づらい

### ISSUE THREAD

**Issue by koiru-2000** [codic-project/codic-vs-extension#15]
配色テーマを「濃色」にしている場合に、入力カーソルが黒色なので、入力欄の背景色と同化して見づらいです。
テキストエディタと同じように、入力カーソルを白色にすることはできないでしょうか？

↓ ス と ト の間に入力カーソルがあるとき
![参考画像](https://user-images.githubusercontent.com/63147321/134754273-a0175594-e947-46a8-9e01-bb2a31cc6c05.png)

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。原因がわかりましたので、修正までしばらくお待ち下さい。
原因：https://www.codeproject.com/Articles/34736/Changing-the-Caret-Colour-in-WPF

**Comment by kenji-namba** [comment]
おまたせしました。
最新バージョン 1.0.9 で対応していますので、ご確認ください。
問題ないようでしたら、ご報告頂けますと助かります。

**Comment by koiru-2000** [comment]
ご対応ありがとうございます。

カーソルが白になることを確認できました。
配色テーマが「淡色」の場合には、しっかり黒にもなりますね。
問題なしです。

ありがとうございました。
