### ISSUE TITLE
変換履歴が存在しない場合、エラーメッセージが出て変換がおこなわれない

### ISSUE THREAD

**Issue by kakunpc** [codic-project/codic-vs-extension#2]
変換を行おうとすると「オブジェクト参照がオブジェクト インスタンスに設定されていません。」とエラーがメッセージが出ます。

問題を調べたところ
[codic-vs-extension/CodicExtension/Model/LetterCase.cs](https://github.com/codic-project/codic-vs-extension/blob/master/CodicExtension/Model/LetterCase.cs#L25-L36)
にて、idにnullが発生し、例外エラーが発生していました。

**Comment by kenji-namba** [comment]
報告ありがとうございました！。
1.0.2で修正されていますので、ご確認ください m(_ _)m。

**Comment by kakunpc** [comment]
対応ありがとうございます！
エラーが出ず、正しく変換がおこなえた事を確認できました。
