### ISSUE TITLE
Visual Studio 2015 Professional Update 1で変換時に必ずVSが落ちる

### ISSUE THREAD

**Issue by for-futurity** [codic-project/codic-vs-extension#3]

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。
お手数ですが、Activity.log のエラーメッセージを頂く事はできますでしょうか。
よろしくお願いいたします。

ログの取得方法は↓ 
https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/

**Comment by ghost** [comment]
340 ERROR Extension will not be loaded because an extension with the same ID 'Microsoft.Windows.DevelopmentKit.Desktop' is already loaded at C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\10\DESKTOP SDK...
          C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.1\DESKTOP SDK\   Extension Manager 2016/03/06 10:56:16.209 
341 ERROR Extension will not be loaded because an extension with the same ID 'Microsoft.Windows.DevelopmentKit.WindowsStore' is already loaded at C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\10\WINDOWS STORE SDK...
          C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.1\WINDOWS STORE SDK\   Extension Manager 2016/03/06 10:56:16.209 

たぶんこれ
ちがったらごめんなさい

**Comment by kenji-namba** [comment]
ありがとうございます。
１点、もし複数のVSバージョンをPCへインストールされている場合は、
そのバージョンを教えて頂けないでしょうか。

**Comment by ghost** [comment]
Microsoft Visual Studio Professional 2013 Version 12.0.40629.00 Update 5
Microsoft Visual Studio Community 2015 Version 14.0.24720.00 Update 1
以上

**Comment by kenji-namba** [comment]
@Rivertop-Osamuta  再現できなかったのですが、当りを付けVersion 1.0.4で少しコードを変更しています。お手数ですが、最新にアップデートして、問題が解決しないか確認頂けますでしょうか？

**Comment by ghost** [comment]
問題は解決しませんでした。ゴメンナサイ。
エラーログも確認しましたが、状況は変わりません。
none53さんの落ち方と全く一緒です。
当たりというものを教えてください。何かできるかもしれません。
また、このエラーは、根拠もない想像ですが拡張機能一つのエラーでVisual Studioが完全に落ちるのも
不思議なのでVisual Studio自体にに問題があったりして....

**Comment by for-futurity** [comment]
落ちるという表現には誤りがありました。
正しくは、動作が停止でした。

1.0.4で試してみましたが、やはり動作停止するようです。

**Comment by kenji-namba** [comment]
みなさんありがとうございました。
返事が遅くなりすいません。

@Rivertop-Osamuta さん
Extension自体は起動しているみたいなので、単語を選択した時の処理に問題があるのかなと推測しています。

作り的に、ダイアログをポップアップ風に見せるためにWindows API ? をごにょごにょしている部分があって、その辺りが原因かなと思い、Windows APIなしバージョンを作ってみました。
すいませんが、時間があるときにでも試していただけないでしょうか。

以下手順です。
1. 今のextensionはアンインストール
2. 下のページを開き「Download」ボタンをクリックしてVSIXをダウンロード
https://github.com/codic-project/codic-vs-extension/blob/sandbox/no-winapi/CodicExtension/CodicExtension_1.0.4_nowinapi.vsix
3. VSIX を実行でインストール

機能をコメントアウトした関係で、ポップアップのリサイズとポップアップ領域外をクリックした際に閉じる機能がありません。ポップアップを閉じるのはESCキーでいけます。

**Comment by ghost** [comment]
遅くなりましてすみません。
まったく状況は変化ありません。
完全に動作を停止しています。

**Comment by kenji-namba** [comment]
@Rivertop-Osamuta さん
ありがとうございました。
うーん ... 暗礁に乗り上げましたね。
やはり、VS Professional 2015を手に入れて、再現を試みるしかなさそうですね。
もう少しお待ちください。

**Comment by kenji-namba** [comment]
Version 1.0.5で対応しています。お手数ですが、1.0.5にアップデートしてみてください。
また、結果をご報告頂けると助かります。

**Comment by fixer-asano** [comment]
VS Professional 2015 update 3 です。
動作に問題なさそうでした。

**Comment by for-futurity** [comment]
VS Professional 2015 update 3です。
動作に問題なさそうでした。

**Comment by ghost** [comment]
めでたく正常作動しました。
今のところ問題はありません。
ご苦労様でした。

**Comment by kenji-namba** [comment]
@for-futurity さん
@Rivertop-Osamuta さん
ご報告ありがとうございます(^^)。
このIssueは、一旦クローズしますね。ご協力ありがとうございました。
