### ISSUE TITLE
生成された関数名を選択すると、VS2015が動作を停止する。

### ISSUE THREAD

**Issue by none53** [codic-project/codic-vs-extension#4]
操作内容
　1. Shift+Ctrl+Dでアプリを起動する。
　2. 日本語を入力する。（ここでは、"フレームをゼロでクリアする"）
　3. 関数名が表示されるので、これを上下のキーで選んで、Enterを押す。
　4. VS2015が停止する。

再現性
　必ず再現します。3/3

環境
　Windows10 Pro バージョン 1607 OS ビルド 14393.51

　Microsoft Visual Studio Enterprise 2015
　Version 14.0.25425.01 Update 3

===エラーログ１=====================================
153 ERROR
Error loading extension: この VSIX は、このコンピューターにインストールされているどの製品にも適用されません。問題として考えられるのは、VSIX マニフェストの形式が認識されないか、マニフェストが破損していることです。 ルート レベルのデータが無効です。 行 1、位置 1。 
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\VSGRAPHICS\
Extension Manager 2016/08/17 10:24:34.215

===エラーログ２=====================================
430 ERROR
Error loading extension: この VSIX は、このコンピューターにインストールされているどの製品にも適用されません。問題として考えられるのは、VSIX マニフェストの形式が認識されないか、マニフェストが破損していることです。 ルート レベルのデータが無効です。 行 1、位置 1。 
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\VSGRAPHICS\
Extension Manager
## 2016/08/17 10:24:34.312

431 ERROR
Extension will not be loaded because an extension with the same ID 'Microsoft.VisualStudio.TeamFoundation.TeamExplorer.Extensions' is already loaded at C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\NCZZXXVV.PPH...
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TEAMFOUNDATION\TEAM EXPLORER\

**Comment by kenji-namba** [comment]
丁寧な報告ありがとうございます。助かります。
Updateを適用してみて再現を試みます。
拡張が読み込めていないのに、ネーミングの生成のダイアログが出ている点が気になりますが ...

以下メモ

```
MEMO :  Error loading extension: This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted. Data at the root level is invalid. Line 1, position 1. 
```

**Comment by kenji-namba** [comment]
@none53 再現できなかったのですが、当りを付けVersion 1.0.4で少しコードを変更しています。お手数ですが、問題が解決しないか確認頂けますでしょうか？

**Comment by none53** [comment]
V1.0.4で試してみましたが、問題の現象が再現しました。うちの環境では、ダメなようです。

[ActivityLog_20160831.zip](https://github.com/codic-project/codic-vs-extension/files/446597/ActivityLog_20160831.zip)

**Comment by kenji-namba** [comment]
ありがとうございます m(_ _)m。
ダメですか... もう少し調べてみます。
ちなみに、開発言語（プロジェクトの種類）は何でしょうか？
また、エディタの種類によって現象が発生するものとしないものがありますでしょうか？。

**Comment by none53** [comment]
> ちなみに、開発言語（プロジェクトの種類）は何でしょうか？
> C#で試しました。
> また、エディタの種類によって現象が発生するものとしないものがありますでしょうか？。
> Visual Studio標準のものでしか試したことがないです。

エラーが出たときの画面を貼っておきます。
![vs2015_cs_clip](https://cloud.githubusercontent.com/assets/960324/18122802/0fe5fcb0-6fa6-11e6-9c9a-3a2a4ed4168a.png)

**Comment by kenji-namba** [comment]
返事が遅くなりすいません。

作り的に、ダイアログをポップアップ風に見せるためにWindows API ? をごにょごにょしている部分があって、その辺りが原因かなと思い、Windows APIなしバージョンを作ってみました。
すいませんが、時間があるときにでも試していただけないでしょうか。

以下手順です。
1. 今のextensionはアンインストール
2. 下のページを開き「Download」ボタンをクリックしてVSIXをダウンロード
https://github.com/codic-project/codic-vs-extension/blob/sandbox/no-winapi/CodicExtension/CodicExtension_1.0.4_nowinapi.vsix
3. VSIX を実行でインストール

機能をコメントアウトした関係で、ポップアップのリサイズとポップアップ領域外をクリックした際に閉じる機能がありません。ポップアップを閉じるのはESCキーでいけます。

**Comment by kenji-namba** [comment]
Version 1.0.5で対応しています。お手数ですが、1.0.5にアップデートしてみてください。
また、結果をご報告頂けると助かります。

**Comment by kenji-namba** [comment]
#3 に関連して、こちらもクローズさせて頂きます。
ご協力ありがとうございました。
